---
title: "Groupby_a"
author: "Lily"
date: "2025-11-25"
output: html_document
---
```{r}

library(terra)
library(ggplot2)
library(dplyr)


clean_data <- read.csv("clean_data/HJ_data.csv")

spec(HJ_data)

clean_data <- HJ_data

spec(clean_data)

names(clean_data)
```

```{r}
clean_data %>%
  group_by(NativePollinator) %>%
  summarise(count = n())
#13579 non native bee individuals
#15974 native bee individuals


clean_data %>%
  group_by(NativePlant) %>%
  summarise(count = n())
#1207 non native plants 
#28346 native plants 

```

```{r}
#creating a summary of the plant, whether non native bees were observed, and the abundance of native bee records 

plants <- clean_data %>%
  group_by(PlantGenusSpecies, NativePlant) %>%
  summarise(non_nativebee_count = sum(NativePollinator == 0),
            nativebee_count = sum(NativePollinator ==1))
plants
table(plants$non_nativebee_count)
#time to see if there is a difference in the counts of native bees due to the presence of non-native bees

```

```{r}
#creating boxplot to compare abundances 

ggplot(plants, aes(x = non_nativebee_count, y = nativebee_count))+
  geom_point() +
  xlim(0,1000)
  labs( x= "Non-native bee presence",
        y = "Native bee abundance",
        title = "Native bee abundance relative to presence non-native bees.")+
  theme(axis.line = element_line(color = "black", size = 0.5))
  scale_color_manual(values = c("Native" = "green", 
                                "Non-native" = "orange")

#need to work out how to make the font bigger for the labels.

```
This is the opposite of our predictions. However one can observe a much larger range in native bee abundances for when non native bees are present. FALSE(n=51), TRUE(n=73). This boxplot includes bee observation from both native and non-native plants.  


now for the line plots 
```{r}
#count how many observations involve native vs non-native plants per month


plant_month_plot <- clean_data %>%
  group_by(Month, NativePlant) %>%
  summarise(plant_abundance = n(), .groups = "drop") #creates a new abundance column that counts number of bee observations corresponding to native vs non-native for each month 

plant_month_plot #shows each month twice, 1 for abundance of native plants (0) and one for abundance of non-native plants (1).

#for the plot we want though:
bee_month_plot <- clean_data %>%
  filter(NativePollinator == 1) %>% 
  group_by(Month, NativePlant) %>%
  summarise(native_bee_abundance = n(), .groups = "drop")%>%
  mutate(count(Month))

bee_month_plot
```


the plots for these 

```{r}
ggplot(plant_month_plot, aes(x = Month, y = plant_abundance, color = factor(NativePlant), group = NativePlant)) +
  geom_line(size = 1.2) +
  geom_point(size = 2) +
  scale_color_manual(values = c("orange", "green"),
                     labels = c("Non-native plants", "Native plants"))+
  labs(x= "Month", y = "Plant abundance",
       color = "Plant type",
       title = "Native vs. Non-native plant abundances by month") +
  theme_minimal()
plant_month_plot

#fairly sure this plot is wrong. start here when I come back to it
```
```{r}
plant_month_plot
```


```{r}
ggplot(bee_month_plot, aes(x = Month, y = native_bee_abundance, color = factor(NativePlant), group = NativePlant)) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = c("red", "green"),
                     labels = c("Non-native plants", "Native plants"))+
  labs(x= "Month", y = "Native bee abundance",
       color = "Plant type",
       title = "Native bee observations on native vs. non-native plants by month") +
  theme_minimal()
bee_month_plot


```
```{r}
bee_month_plot

#in July native bee abundance peaks 
```
```{r}
#for non native and native plants, divide visitation of native bees by total number of native bee observations for each month then can compare each month
new_plot <- clean_data %>%
  filter(NativePollinator==1)%>%
  group_by(Month, NativePlant) %>%
  summarize(obs= n(), .groups = "drop")%>%
  group_by(Month)%>%
  mutate(total_visits = sum(visits),
         proportion = visits / total_visits
  )
  new_plot

colnames(clean_data)
#take the difference between native and non-native plant abundance per month, and create a line plot.
```
```{r}
#find the proportion, divide by number of observations of native bees for each month then can compare each month.
test_plot <- clean_data %>%
  filter(NativePollinator == 1) %>% 
  group_by(Month, NativePlant) %>%
  summarise(native_bee_abundance = n(), .groups = "drop") %>%
  group_by(Month)%>% #total native bee obs per month
  mutate(total_native_bees = sum(native_bee_abundance),
         proportion = native_bee_abundance / total_native_bees) %>% #creating new column 'proportion'
  ungroup()

test_plot


```

```{r}
#plotting 
ggplot(test_plot, aes(x=Month, y=proportion,
                           color = factor(NativePlant), group = NativePlant))+
  geom_line(size = 0.5) +
  geom_point(size = 2) +
  scale_color_manual(values = c("orange","green"),
                     labels = c("Non-native plant species", "Native plant species")) +
  labs(x = "Month",
       y = "Proportion of native pollinator observations",
       color = "Type of plant on which\nthe pollinator was observed",
       title = "Proportion of native pollinator observations\non native vs. non-native plants by month.") +
  theme(axis.line = element_line(color = "black", size = 0.5))

```


