---
title: "Network"
output: html_document
date: "2025-11-30"
---

read in cleaned data
```{r}
clean_data<- read.csv("clean_data/HJ_data.csv")
```

keep only two necessary columns for this visualization
```{r}
library(tidyr)
library(dplyr)

##select only relevant columns- PollinatorGenusSpecies and PlantGenusSpecies
interactions<- clean_data %>%
  select(PollinatorGenusSpecies, PlantGenusSpecies)
```

##need to convert dataframe to matrix with bee species columns and plant rows
convert data frame into adjacency matrix
```{r}
## table the dataframe to sum up interactions between each plant and pollinator species and unclass it as a table so it is recognized as a matrix
interactions_adj<- unclass(table(interactions))

#check class- should be matrix
class(interactions_adj)
```

convert matrix to igraph object
```{r}
library(igraph)

## convert regular adjacency matrix to igraph bipartite adjacency matrix
# use weight=TRUE to preserve the strength of interactions (when there is more than 1 observation of a bee species interacting with a given plant species)
interactions_igraph <- graph_from_biadjacency_matrix(interactions_adj, weight=TRUE)

# check class- should be igraph
class(interactions_igraph)
```

convert igraph to a network 3d object
```{r}
library(networkD3)

### find modules in order to use as vertices
int_modules <- cluster_walktrap(interactions_igraph)

### assign vertices to modules
groups <- membership(int_modules)

### convert igraph to a network 3d object, using the modules as node values
interactions_net3d <- igraph_to_networkD3(interactions_igraph, group=groups, 
                                       what = "both")

## check that it has two list items to use for network visualization- links and nodes
str(interactions_net3d)
```

make network visualization- we chose the Sankey plot
```{r}
sankeyNetwork(Links = interactions_net3d$links,
             Nodes = interactions_net3d$nodes,
            Source = "source", Target = "target",
            Value = "value",  NodeID = "name", 
            nodePadding = 0, height = 500)
```

