---
title: "Lit_review_JR_LL"
output: html_document
date: "2025-11-06"
---

Paragraph 1: intro, problem and significance 
Invasive species are known to have a negative impact on native species and ecosystems around the world. Non-native plant invasions contribute to dwindling populations of native plant species that are ecologically and culturally important. Similarly, non-native pollinators can outcompete native species and contribute to population decline (Maureen 2022). This can further affect native plants that rely on native pollinators for efficient pollination if invasive species don’t replace the same functions. However, the specific effects invasions can have on plant-pollinator interactions can vary. A review paper by (Traveset 2009) explains that invasive pollinators can have little to no impact on native plant-pollinator mutualism if it is a highly specialized relationship because invasive pollinators tend to be generalists and will interact with a wider variety of plant species. Invasive plants can have more of an impact on these native mutualisms, especially if they are more attractive to native pollinators and outcompete native plants. However, this may not be the case for highly specialized relationships.
With respect to plants, non-native or ‘alien’ species have been evidenced to negatively impact visitation rates and reproduction of native co-flowering focal species (Morales 2009). This highlights the point at which non-native plant species become an issue as they have the potential to dominant landscapes and alter plant community and structure. This is turn could likely impact the abundance of native plant and pollinator interactions, again altering plant-pollinator dynamics. 
Invasive pollinators and plants may even interact with each other to have a greater impact on native plant-pollinator communities. For example, (Barthell 2001) investigated the interactions between an invasive bee, Apis mellifera, and an invasive plant, Centaurea solstitialis, and found that A. mellifera increases the reproductive success of C. solstitialis, suggesting that invasive plant-pollinator mutualisms could contribute to more successful plant invasions, further impacting native plant-pollinator interactions.


Paragraph 2- past work and data available 
	With all of these variable effects, it is important to understand native plant-pollinator interactions locally in order to better predict how invasions may impact the community in a certain place. More specific place-based studies have investigated how invasive pollinators can impact native plant-pollinator communities, primarily due to competition with native pollinators. For example, (Dohzono 2008) found that a Japanese native bumblebee Bombus ardens visited a native plant, Corydalis ambigua, much less frequently when the invasive Bombus terrestris visited. This resulted in lower reproduction for the plant because B. terrestris robs nectar without contributing to pollination. Most of the research on invasive pollinators centers on the very successful Apis mellifera, or European honeybee, which has been brought all over the world to live alongside agricultural fields in order to pollinate crops and make honey. But their introduction into any ecosystem can have an impact on native bees and plants. For example, when (Thomson) studied the interactions between a California native social bee, B. occidentalis, and A. mellifera, they found that B. occidentalis colonies located closer to A. mellifera hives had lower reproductive success, which could have a further impact on plant species that rely on this native bee. Another study focussing on the impact of the introduced honeybee (Dupont 2003) found that these pollinators can disrupt native pollination networks by altering foraging behaviours and increasing competition for nectar in flowering populations. 
Similarly in a meta-analysis paper published by Laura Morales (2009), the effects of visitation rate and reproduction are monitored for native plant species located next near to alien plant species. The paper highlighted interestingly the two proposed most important properties of alien plant species competing for more pollinator interactions being floral abundance and the similarity of floral morphologies with native plants. The latter in particular can cause problems like the encouragement of native bees to pollinate nonnatives, and specialist plants being over competed.  
However, in a study by (Borchardt 2025) on native plant-pollinator interactions in prairie strips alongside agricultural fields in California, they found little to no impact of A. mellifera presence on native bee community composition from June to August. From another angle, (Barthell 2001) investigated the interactions between A. mellifera and an invasive plant, Centaurea solstitialis, and found that A. mellifera increases the reproductive success of C. solstitialis, suggesting that invasive plant-pollinator mutualisms could contribute to more successful plant invasions, further impacting native plant-pollinator interactions. Similarly, Spessa A (1999) studied the impact of honeybee presence on a native colletid bee A. morosus and detected no ‘negative impact’, concluding that nectar and pollen were not limiting for A. morosus and the null hypothesis was accepted, even though there was a resource overlap between these two study species. After comparing these studies, it alludes that different species of pollinator will be limited by different factors (Paini 2004)
Most of the research into how invasive species, especially pollinators like A. mellifera, impact native plant-pollinator interactions are situated close to more human-altered landscapes, such as agricultural areas. There is less research into native plant-pollinator interactions and how invasive species alter them in more remote areas. In our research, we investigate native plant-pollinator associations in high-elevation meadows, which are further from dense human populations. There may not be as much of an invasive bee impact here, especially due to the lack of commercial beekeeping. We also investigate how native plant-pollinator interactions may change over time, which hasn’t been closely studied. 
We use plant-pollinator network data from the HJ Andrews experimental forest in order to explore these interactions. This data was collected in high-elevation meadows in the HJ Andrews experimental forest. It includes pollinator observations at different plant focals and data on focal plant and pollinator taxonomy, date of observations, site and plot of observations, and much more. We will primarily be using the identification of plants and pollinators and the date of observations. We also use plant databases, such as Oregon Flora and Cal flora in order to identify which plants in the data are native or non-native. Our professor Lauren Ponisio gave us the most common non-native bee species present in the research site. We assume all other bee species are native.

Paragraph 3: purpose of this study 
The purpose of this study is to explore native plant-pollinator interactions in high-elevation meadows in the HJ Andrews Experimental Forest, Oregon, with the aim to interpret quantified dynamics of interactions between native and non-native bees and native and non-native plant species specific to this ecoregion. 
With our chosen dataset, we aim to explore 3 main questions:
What plants do native bees more strongly associate with in high-elevation meadows in Oregon? Are they more often native or non-native?
Do non-native bees compete with native bees for access to native plants in these meadows?
How do the interactions between native bees and their preferred plants change over the growing season in high-elevation meadows?
To help answer these questions, our hypotheses are as follows:
We predict native bees will more strongly associate with native plants in high-elevation meadows in Oregon. This is because it is likely that native bees and plants would have coexisted for longer in history than non-natives, meaning that native plant-pollinator interactions are likely to be more specialised or adapted to each other for example floral morphology, nectar and flower phenology, resulting in closer bee-native-plant associations. More specifically for plants growing in montane regions, they have to adapt to perhaps more harsh conditions compared with other ecoregions.
We predict that there will be little to no significant change in native plant-pollinator relationships in the presence of non-native bees. This is because in montane regions, there are environmental constraints like shorter growing seasons that lead to non-native, introduced species cannot compete with better adapted natives as well, also we predict there will be a higher abundance of native bee species in this region in general,  so non-natives will be outnumbered, making these effects less likely or less significant. 
We also predict that native bees may shift to stronger associations with non-native plants later in the growing season due to potentially later blooming non-native species. This is because native plants may likely flower in an earlier, narrower window of growing season in montane regions, meaning bees may have to shift to more generalised non-natives that bloom later in the season, or perhaps for a longer proportion of the year.
We aim to create a visualisation network to envisage plant-pollinator interactions of native bee species with both native and non-native flora present in our focal dataset. 
The study of plant pollinator interaction networks is important now due study systems of high elevation montane meadows being understudied compared to more urban, agricultural studies of pollinators. It is important to make visualisation of these ecosystems now for conservation purposes so we can more easily track how potential future disturbances (invasives but also other external influences for example changes in climate and land-use) affects the structure of these communities in generations to come. 
Our findings will provide insight into which plant communities are most productive for native bees in high elevation meadows, whether there is interspecific competition for the same resources between native and non-native bees in this ecosystem, and lastly how these dynamics may be amplified or dampened over seasonal time periods.

References:

Barthell, J. F., Randall, J. M., Thorp, R. W., & Wenner, A. M. (2001). Promotion of Seed Set in Yellow Star-Thistle by Honey Bees: Evidence of an Invasive Mutualism. Ecological Applications, 11(6), 1870–1883. https://doi.org/10.1890/1051-0761(2001)011%255B1870:POSSIY%255D2.0.CO;2 
Borchardt, K. E., Moore, M., Cass, R., O’Neal, M., & Toth, A. L. (2025). Are honey bees altering wild plant–bee interactions in reconstructed native habitats? An investigation of summer season effects in row-crop agroecosystems with prairie strips. Ecological Entomology, 50(5), 807–823. https://doi.org/10.1111/een.13448 
Dupont, Y., Hansen, D., Valido, A., Olesen, J. (2003). Impact of introduced honey bees on native pollination interactions of the endemic Echium wildpretii (Boraginaceae) on Tenerife, Canary Islands. Biological Conservation, 118(2004),  https://doi:10.1016/j.biocon.2003.09.010
Dohzono, I., Kunitake, Y. K., Yokoyama, J., & Goka, K. (2008). Alien Bumble Bee Affects Native Plant Reproduction through Interactions with Native Bumble Bees. Ecology, 89(11), 3082–3092. https://doi.org/10.1890/07-1491.1 
Morales, C., Traveset, A. (2009). A meta-analysis of impacts of alien vs native plants on pollinator visitation and reproductive success of co-flowering native plants. Ecology, 12(7), 716-728. https://doi.org/10.1111/j.1461-0248.2009.01319.x
Paini (2004). Impact of the introduced honey bee (Apis mellifera) (Hymenoptera: Apidae) on native bees: A review. Austral Ecology, 29, 399-407.
Spessa A. (1999) Behavioural and population ecology of an Australian native bee, Amphylaeus morosus (Colletidae: Hylaeinae). PhD Thesis, Australian National University, Canberra, Australian Capital Territory, Australia.
Thomson, D. (2004). Competitive Interactions Between the Invasive European Honey Bee and Native Bumble Bees. Ecology, 85(2), 458–470. https://doi.org/10.1890/02-0626 
Traveset, A., & Richardson, D. (2006). Biological invasions as disruptors of plant reproductive mutualisms. Trends in Ecology & Evolution, 21(4), 208–216. https://doi.org/10.1016/j.tree.2006.01.006 

