---
title: "Workflow_and_lit_review"
output: html_document
date: "2025-11-15"
---
# HJ Andrews plant-pollinator interactions between native and non-native species

**Partner(s):** Lily Lawrence and Jordynn Risdal

## Literature review

  Invasive species are known to have a negative impact on native species and ecosystems around the world. Non-native plant invasions contribute to dwindling populations of native plant species that are ecologically and culturally important. Similarly, non-native pollinators can outcompete native species and contribute to population decline. This can further affect native plants that rely on native pollinators for efficient pollination if invasive species don’t replace the same functions. However, the specific effects invasions can have on plant-pollinator interactions can vary. A review paper by @Traveset_2006 explains that invasive pollinators can have little to no impact on highly specialized native plant-pollinator mutualisms because invasive pollinators tend to be generalists and will interact with a wider variety of plant species. Invasive plants can have more of an impact on these native mutualisms, especially if they are more attractive to native pollinators and outcompete native plants. A study by @Morales_2009  found that native or ‘alien’ species can negatively impact pollinator visitation rates and reproduction of native co-flowering focal species, which may contribute to their ability to dominate landscapes and alter plant community and structure. Invasive pollinators and plants may even interact with each other to have a greater impact on native plant-pollinator communities. For example, @Barthell_2001 investigated the interactions between an invasive bee, Apis mellifera, and an invasive plant, Centaurea solstitialis, and found that A. mellifera increases the reproductive success of C. solstitialis, suggesting that invasive plant-pollinator mutualisms could contribute to more successful plant invasions, further impacting native plant-pollinator interactions.

  With all of these variable effects, it is important to understand native plant-pollinator interactions locally in order to better predict how invasions may impact the community in a certain place. More specific place-based studies have investigated how invasive pollinators can impact native plant-pollinator communities, primarily due to competition with native pollinators. For example, @Dohzono_2008 found that a Japanese native bumblebee Bombus ardens visited a native plant, Corydalis ambigua, much less frequently when the invasive Bombus terrestris visited. This resulted in lower reproduction for the plant because B. terrestris robs nectar without contributing to pollination. Most of the research on invasive pollinators centers on the very successful Apis mellifera, or European honeybee, which has been brought all over the world to live alongside agricultural fields in order to pollinate crops and make honey. But their introduction into any ecosystem can have an impact on native bees and plants. For example, when @Thomson_2004 studied the interactions between a California native social bee, B. occidentalis, and A. mellifera, they found that B. occidentalis colonies located closer to A. mellifera hives had lower reproductive success, which could have a further impact on plant species that rely on this native bee. Another study by @Dupont_2004 focusing on the impact of A. mellifera found that these pollinators can disrupt native pollination networks by altering native bee foraging behaviours and increasing competition for nectar in flowering populations. Similarly in a meta-analysis paper, @Morales_2009 monitored visitation rate and reproductive success of native plant species located next to alien plant species. The paper proposed that the two most important properties of alien plant competition are floral abundance and the similarity of floral morphologies with native plants. The latter in particular can encourage native bees to pollinate non-natives, while specialist native plants are out-competed.  

  However, not all research has found a negative impact of invasive species on native plant-pollinator networks. In a study by @Borchardt_2025 on plant-pollinator interactions in prairie strips alongside agricultural fields in California, they found little to no impact of A. mellifera presence on native bee community composition from June to August. Similarly, @Spessa_1999 studied the impact of honeybee presence on a native colletid bee Amphylaeus morosus and detected no negative impact, concluding that nectar and pollen were not limiting for A. morosus and the null hypothesis was accepted, even though there was a resource overlap between the two study species. With the variable results from different studies, it stands to reason that different species of pollinator will be limited by different factors @Paini_2004.

  Most of the research into how invasive species, especially pollinators like A. mellifera, impact native plant-pollinator interactions are situated close to more human-altered landscapes, such as agricultural areas. There is less research into native plant-pollinator interactions and how invasive species alter them in more remote areas. In our research, we investigate native plant-pollinator associations in high-elevation meadows, which are further from dense human populations. There may not be as much of an invasive bee impact here, especially due to the lack of commercial beekeeping. We use plant-pollinator network data from the HJ Andrews experimental forest in order to explore these interactions. This data was collected in high-elevation meadows in the HJ Andrews experimental forest. It includes pollinator observations at different plant focals and data on focal plant and pollinator taxonomy, date of observation, site and plot of observation, and much more. We primarily use the identification of plants and pollinators and the date of observations. We also use plant databases, such as Oregon Flora and Calflora in order to identify which plants in the data are native or non-native. We have a list of the most common non-native bee species present in the research site. We assume all other bee species are native.

  We aim to use this data to explore 3 main questions: (1) What plants do native bees more strongly associate with in high-elevation meadows in Oregon? Are they more often native or non-native? (2) Do non-native bees compete with native bees for access to native plants in these meadows? and (3) How do the interactions between native bees and their preferred plants change over the growing season in high-elevation meadows? We first predict that native bees will more strongly associate with native plants in high-elevation meadows in Oregon. This is because native bees and plants have coexisted for longer and may have coevolved to be more specialized, especially in montane regions which have forced them to adapt to harsher conditions compared with other ecoregions. We also predict that there will be little to no significant change in native plant-pollinator relationships in the presence of non-native bees due to a low presence of non-native bees. We expect a lower presence of non-native bees because the montane study region may have environmental constraints that lead to native species easily out-competing non-native species that aren’t so well adapted and haven’t historically been introduced here like A. mellifera has in agricultural areas. Finally, we predict that native bees may shift to stronger associations with non-native plants later in the growing season due to potentially later blooming non-native species, while native species may bloom earlier.

  Our findings will provide insight into how invasive plants impact interactions between native plants and bees in high elevation meadows, whether there is interspecific competition for native plant resources between native and non-native bees in this ecosystem, and how these dynamics may be amplified or dampened over phenological time. The study of these interactions in this region is important because wilder areas have been understudied compared to urban and agricultural areas and plant-pollinator networks have been shown to react to invasion differently depending on the species and location. We need to better understand these interactions to track how potential future disturbances, such as invasions, may affect the structure of these communities. 


## Dataset identification

Primary dataset:
HJ Andrews plant-pollinator interactions
This data was collected in high-elevation meadows in the HJ Andrews experimental forest. It includes pollinator observations at different plant focals and data on focal plant and pollinator taxonomy, date of observations, site and plot of observations, and much more. We will primarily be using the identification of plants and pollinators and the date of observations.

Other Datasets:
https://oregonflora.org/ 
- Oregon Flora is a program owned by the department of Botany and Plant Pathology at Oregon State University
- The database aggregates data from multiple different partners that was collected by many different parties and people.
https://www.calflora.org/
- Calflora is a non-profit
- The database aggregates data from a wide variety of sources collected by many different parties and people.

- We will use Oregon Flora and Calflora to help us identify which plants are native and non-native
- Both of these are searchable databases that don't have columns that correspond to the species and native or non-native but we can use them to find out whether or not a plant species is native.
- We will create 2 new columns to include this data: 1 for whether the observed bee is native and one for whether the focal plant is native.

We also have a list of the most common non-native bee species:
Apis mellifera (European honey bee)
Megachile rotundata (alfalfa leafcutting bee)
Anthidium manicatum (European wool-carder bee)
Osmia cornifrons (horned-faced/orchard mason bee)


## Workflow plan

Step 1: Convert excel file of HJ Andrews dataset into a csv and read in to R

Step 2: Clean data
a. Get rid of unneeded columns- Temp stuff, wind stuff, , unique ID??, collector, order, family, subgenus, determiner, author, 
b. Get rid of rows that have empty plant or bee genus species (or not, maybe genus enough for some bees?)

Step 3: add two columns to identify both bee species and plant species as native or non-native (1 for native, 0 for non-native). We use Calflora and Oregon flora to determine native plant species and Lauren gave us list of most common non-native bee species.
a. Use a for loop- if bee species is one of the listed non-natives, mark 0 for that row, or else mark 1
b. Can use a for loop- if plant species matches "genus species", mark as either 0 or 1, depending on if that species is native or non-native

Step 4: start analysis
A. Group all native and non-native bees to see if there is a difference in abundance overall
- Compare number of rows with native bees to number of rows with non-native bees
- If there is little non-native abundance, our question 2 about competition between native and non-native bees may not be interesting for us.
- If there are still plenty of non-native bees, we can group by plants with and without non-native bee presence and compare with a boxplot to see if there is a difference in native bee abundance. This would be for question 2.

B. Create interaction network to visualize interactions between all plant and bee species
- Also group native plants and non-native plants and group native bees and non-native bees and create interaction network between groups to see if we can see a clear difference in strength of interactions. This would be for question 1 about how strongly native bees associate with native vs. non-native plants.
- Probably use Sankey interaction network

C. AB test:
- Null hypothesis: there is no difference in native bee abundance between between native and non-native plants.
- Alternative hypothesis: there is higher native bee abundance at native plants than non-native plants.
- Groups are native and non-native plants
- Test statistic is the difference in mean abundances of native bees observed at native vs. non-native plants
- Labels of native and non-native plants would be shuffled and test statistic recalculated to generate a histogram and p-value to determine if there is a significant difference between groups
- We will need a function to calculate the test statistic:
- - It will group by native and non-native plants to calculate the abundance of native bee visits at each.
- - It will then calculate the difference between those abundances and that is the test statistic
- We will need a second function that uses the first function to run a permutation test:
- - It will reshuffle the native plant and non-native plant labels and re-run the above function to generate a new statistic
- We will then need a for loop to run the AB test:
- - It will take the second function to reshuffle and re-run the test statistic over a number of loops to generate a vector of statistics
- We will then plot these statistics and compare the observed statistic to the histogram to see if there is a significant difference between the two groups (native and non-native plants).
- This will also be for question 1.

D. Create line plot of non-native plant abundances by month and native plant abundances by month. One line for each.
- This could help tell us if there is a change in the type of flora available to native bees over the course of the year. This would be for question 3, which asks if there is a change in what kinds of plants native bees associate with over the course of the year.

E. Create line plot of native bee abundance at native plants over the months and native bee abundance at non-native plants over the months. One line for each.
- This would help us visualize whether native bees change their food sources over time as non-native plants may become more abundant while native plants become less abundant.
- We could compare this line plot to the one above to see if there is a pattern that is similar between the two.
